# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fomouser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='gender',
            field=models.TextField(blank=True, choices=[['male', 'Male'], ['female', 'Female'], ['transgender', 'Transgender'], ['undefined', 'Undefined']], null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='stateinitial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='zipcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
